# Questão 3 - Custos de Importação

## Carregar o arquivo JSON e gere um novo arquivo CSV organizando-o de acordo com a definição na imagem abaixo.

In [1]:
import pandas as pd
import json

In [2]:
# 1. Carregar o arquivo JSON original
with open('datasets/custos_importacao.json', 'r', encoding='utf-8') as f:
    dados_brutos = json.load(f)

In [3]:
# 2. Normalizar os dados usando a chave correta: 'historic_data'

# A função json_normalize vai 'achatar' a lista historic_data 
# e replicar os campos do produto para cada registro de preço.
df_custos = pd.json_normalize(
    dados_brutos, 
    record_path=['historic_data'], 
    meta=['product_id', 'product_name', 'category']
)
df_custos

,start_date,usd_price,product_id,product_name,category
0,10/08/2016,10583.63,1,Transponder AIS Maré Magnum,eletrônicos
1,15/06/2018,8778.36,1,Transponder AIS Maré Magnum,eletrônicos
2,25/09/2018,8023.87,1,Transponder AIS Maré Magnum,eletrônicos
3,19/03/2019,8772.78,1,Transponder AIS Maré Magnum,eletrônicos
4,17/01/2020,7918.18,1,Transponder AIS Maré Magnum,eletrônicos
...,...,...,...,...,...
1255,01/06/2023,326.88,150,Cabo de Nylon Danforth Magnum Vox,ancoragem
1256,31/01/2024,332.26,150,Cabo de Nylon Danforth Magnum Vox,ancoragem
1257,29/08/2024,292.03,150,Cabo de Nylon Danforth Magnum Vox,ancoragem
1258,04/10/2024,300.96,150,Cabo de Nylon Danforth Magnum Vox,ancoragem
1259,25/10/2024,288.90,150,Cabo de Nylon Danforth Magnum Vox,ancoragem

In [4]:
# 3. Reordenar e renomear colunas para o padrão definido
df_custos = df_custos[['product_id', 'product_name', 'category', 'start_date', 'usd_price']]

In [5]:
#Análise exploratória rapida
df_custos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1260 non-null   object
 1   product_name  1260 non-null   object
 2   category      1260 non-null   object
 3   start_date    1260 non-null   object
 4   usd_price     1260 non-null   float64
dtypes: float64(1), object(4)
memory usage: 49.3+ KB

In [6]:
# 4. Conversão de tipos para garantir a integridade solicitada pela diretoria
df_custos['product_id'] = df_custos['product_id'].astype(int)
df_custos['usd_price'] = df_custos['usd_price'].astype(float)

# Padronizando o formato da data (ex: 10/08/2016 para o padrão ISO YYYY-MM-DD)
df_custos['start_date'] = pd.to_datetime(df_custos['start_date'], dayfirst=True).dt.date

In [7]:
df_custos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1260 non-null   int64
 1   product_name  1260 non-null   object
 2   category      1260 non-null   object
 3   start_date    1260 non-null   object
 4   usd_price     1260 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 49.3+ KB

In [8]:
df_custos.sample(20)

,product_id,product_name,category,start_date,usd_price
179,21,GPS AIS Nautic Thrust,eletrônicos,2017-09-04,2783.21
266,31,Transponder Furuno Pulse Axis,eletrônicos,2016-01-15,2050.48
103,13,Radar Simrad Boost,eletrônicos,2018-01-08,2394.70
247,27,GPS Garmin Vortex Maré Drift,eletrônicos,2025-05-26,2916.55
65,9,Transponder AIS Titan Pulse,eletrônicos,2024-04-16,7544.56
674,79,Motor Diesel Tohatsu Zenith 60HP,propulsão,2025-01-27,11161.01
974,119,Âncora Bruce Aqua,ancoragem,2016-05-19,904.47
128,16,Sonda Garmin Axis,eletrônicos,2018-02-19,9278.00
305,36,Radar Lowrance Aqua Pulse,eletrônicos,2017-10-24,6961.99
916,109,Cabo de Nylon Danforth Evo Aqua Mako,ancoragem,2018-05-16,169.23
434,50,Piloto Automático Simrad Poseidon Magnum,eletrônicos,2023-07-31,2378.45
684,81,Motor Elétrico Torqeedo Barracuda Magnum Helix...,propulsão,2016-07-22,37185.97
1219,147,Corrente Danforth Force Leviathan Impulse,ancoragem,2016-05-13,864.87
81,11,GPS Furuno Swift Leviathan Poseidon,eletrônicos,2018-04-23,10527.94
44,6,Transponder AIS Vector,eletrônicos,2024-03-07,2394.79
680,80,Motor de Popa Volvo Maré 69HP,propulsão,2022-10-28,24177.04
678,80,Motor de Popa Volvo Maré 69HP,propulsão,2021-07-16,25370.34
229,26,Piloto Automático Furuno Core Boost Flux,eletrônicos,2018-04-23,5021.99
754,90,Motor de Popa Yamaha Thrust Marlin Nexus 182HP,propulsão,2023-12-08,16092.39
1182,143,Âncora Delta Hydra Kraken Velocity,ancoragem,2018-04-19,1305.95

In [9]:
# 5. Salvar o resultado final em CSV
df_custos.to_csv('datasets/custos_importacao_normalizado.csv', index=False)

In [10]:
print("Normalização concluída com sucesso. Arquivo 'custos_importacao_normalizado.csv' gerado.")

Normalização concluída com sucesso. Arquivo 'custos_importacao_normalizado.csv' gerado.

In [11]:
df_custos['start_date'].min()

datetime.date(2016, 1, 4)

In [12]:
df_custos['start_date'].max()

datetime.date(2025, 12, 31)